on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
name: Lint
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v3
      with:
        go-version: 1.20.x
    - uses: actions/checkout@v3
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v2
      with:
        skip-go-installation: true
        version: latest
        args: --timeout 3m --verbose
